-- SQL Migration: 20260918200003_ucest105_module3_loops.sql
-- Module 3: For Loops and While Loops with LoopVisualizer

INSERT INTO public.python_course_lessons (id, module_number, level_number, lesson_order, title, estimated_minutes, skill_tags, is_free_preview, active, content)
VALUES
-- Level 9: For Loops
(
  'm3-why-loops', 3, 9, 1, 'Why Repetition Exists', 5, ARRAY['for-loop'], false, true,
  '[
    {
      "id": "t1",
      "type": "teacher-explanation",
      "content": {
        "title": "Automating Repetition",
        "content": "Imagine printing numbers from 1 to 1000. Writing 1000 print statements is tedious and error-prone.\n\nLoops allow us to execute a block of code repeatedly with different values of a loop variable."
      }
    }
  ]'::jsonb
),
(
  'm3-meet-for-loop', 3, 9, 2, 'Meet the for Loop', 8, ARRAY['for-loop'], false, true,
  '[
    {
      "id": "t1",
      "type": "teacher-explanation",
      "content": {
        "title": "Structure of a for Loop",
        "content": "A `for` loop iterates over a sequence (such as numbers generated by `range()`).\n\nSyntax:\nfor i in range(5):\n    print(i)\n\nThis prints 0, 1, 2, 3, 4."
      }
    },
    {
      "id": "vis1",
      "type": "loop-visualizer",
      "content": {
        "steps": [
          { "variables": { "i": 0 }, "output": "0" },
          { "variables": { "i": 1 }, "output": "0\n1" },
          { "variables": { "i": 2 }, "output": "0\n1\n2" },
          { "variables": { "i": 3 }, "output": "0\n1\n2\n3" },
          { "variables": { "i": 4 }, "output": "0\n1\n2\n3\n4" }
        ]
      }
    }
  ]'::jsonb
),
(
  'm3-range-stop', 3, 9, 3, 'range(stop)', 7, ARRAY['for-loop'], false, true,
  '[
    {
      "id": "t1",
      "type": "teacher-explanation",
      "content": {
        "title": "Understanding range(stop)",
        "content": "`range(n)` generates integers from 0 up to (n - 1).\n\nKey Rule: `range(stop)` stops BEFORE reaching the stop value!"
      }
    },
    {
      "id": "po1",
      "type": "predict-output",
      "content": {
        "question": "What is the last number printed by `for i in range(4): print(i)`?",
        "options": ["4", "3", "5", "0"],
        "correctAnswer": 1,
        "explanation": "range(4) yields 0, 1, 2, 3. The stop value 4 is excluded."
      }
    }
  ]'::jsonb
),
(
  'm3-range-start-stop', 3, 9, 4, 'range(start, stop)', 7, ARRAY['for-loop'], false, true,
  '[
    {
      "id": "t1",
      "type": "teacher-explanation",
      "content": {
        "title": "Setting a Custom Start Value",
        "content": "`range(start, stop)` starts at `start` and stops at `stop - 1`.\n\nExample:\nfor i in range(1, 6):\n    print(i) # prints 1, 2, 3, 4, 5"
      }
    },
    {
      "id": "cp1",
      "type": "code-practice",
      "content": {
        "instruction": "Write a loop to print numbers from 10 to 15 (inclusive).",
        "starterCode": "for i in range(10, 16):\n    print(i)",
        "solutionCode": "for i in range(10, 16):\n    print(i)",
        "testCases": [
          { "input": "", "expectedOutput": "10\n11\n12\n13\n14\n15" }
        ]
      }
    }
  ]'::jsonb
),
(
  'm3-range-step', 3, 9, 5, 'range(start, stop, step)', 7, ARRAY['for-loop'], false, true,
  '[
    {
      "id": "t1",
      "type": "teacher-explanation",
      "content": {
        "title": "Stepping Through Sequences",
        "content": "`range(start, stop, step)` increments by `step` on each iteration.\n\nExample:\nfor i in range(2, 11, 2):\n    print(i) # prints 2, 4, 6, 8, 10"
      }
    }
  ]'::jsonb
),
(
  'm3-negative-steps', 3, 9, 6, 'Negative Steps', 6, ARRAY['for-loop'], false, true,
  '[
    {
      "id": "t1",
      "type": "teacher-explanation",
      "content": {
        "title": "Counting Down with Negative Step",
        "content": "To count backwards, use a negative step value.\n\nExample (Syllabus problem: 50 down to 1):\nfor i in range(50, 0, -1):\n    print(i)"
      }
    }
  ]'::jsonb
),
(
  'm3-counters-accumulators', 3, 9, 7, 'Counters and Accumulators', 8, ARRAY['for-loop', 'variable'], false, true,
  '[
    {
      "id": "t1",
      "type": "teacher-explanation",
      "content": {
        "title": "Accumulating Results",
        "content": "An accumulator variable stores a running total.\n\nExample (Sum of first N numbers):\ntotal = 0\nfor i in range(1, 6):\n    total += i\nprint(total) # 15"
      }
    },
    {
      "id": "vis1",
      "type": "loop-visualizer",
      "content": {
        "steps": [
          { "variables": { "i": 1, "total": 1 }, "output": "total = 1" },
          { "variables": { "i": 2, "total": 3 }, "output": "total = 3" },
          { "variables": { "i": 3, "total": 6 }, "output": "total = 6" },
          { "variables": { "i": 4, "total": 10 }, "output": "total = 10" },
          { "variables": { "i": 5, "total": 15 }, "output": "total = 15" }
        ]
      }
    }
  ]'::jsonb
),
(
  'm3-nested-loop-intro', 3, 9, 8, 'Nested Loop Introduction', 7, ARRAY['for-loop'], false, true,
  '[
    {
      "id": "t1",
      "type": "teacher-explanation",
      "content": {
        "title": "Loops Inside Loops",
        "content": "A nested loop is a loop inside another loop. The inner loop completes ALL its iterations for EACH single iteration of the outer loop.\n\nUsed for patterns, grids, and 2D matrices."
      }
    }
  ]'::jsonb
),
(
  'm3-for-loop-practice', 3, 9, 9, 'For Loop Practice', 10, ARRAY['for-loop'], false, true,
  '[
    {
      "id": "cp1",
      "type": "code-practice",
      "content": {
        "instruction": "Write a program using a for loop to calculate the factorial of 5 (5 * 4 * 3 * 2 * 1 = 120).",
        "starterCode": "fact = 1\nfor i in range(1, 6):\n    fact *= i\nprint(fact)",
        "solutionCode": "fact = 1\nfor i in range(1, 6):\n    fact *= i\nprint(fact)",
        "testCases": [
          { "input": "", "expectedOutput": "120" }
        ]
      }
    }
  ]'::jsonb
),
(
  'm3-for-loop-checkpoint', 3, 9, 10, 'For-Loop Checkpoint', 8, ARRAY['for-loop'], false, true,
  '[
    {
      "id": "quiz1",
      "type": "checkpoint-quiz",
      "content": {
        "passingScore": 70,
        "questions": [
          {
            "id": "q1",
            "question": "What is the output of len(list(range(2, 10, 2)))?",
            "options": ["4", "5", "8", "3"],
            "correctAnswer": 0,
            "explanation": "range(2, 10, 2) produces [2, 4, 6, 8], which has length 4."
          },
          {
            "id": "q2",
            "question": "Which range expression generates numbers from 5 down to 1?",
            "options": ["range(5, 0, -1)", "range(5, 1, -1)", "range(5, 0, 1)", "range(1, 5)"],
            "correctAnswer": 0,
            "explanation": "range(5, 0, -1) starts at 5 and stops at 1."
          }
        ]
      }
    }
  ]'::jsonb
),

-- Level 10: While Loops
(
  'm3-why-while', 3, 10, 1, 'Meet while', 5, ARRAY['while-loop'], false, true,
  '[
    {
      "id": "t1",
      "type": "teacher-explanation",
      "content": {
        "title": "Condition-Driven Repetition",
        "content": "A `while` loop repeats as long as a Boolean condition remains True.\n\nUse `while` when you don't know in advance how many times the loop should run."
      }
    }
  ]'::jsonb
),
(
  'm3-while-init-condition-update', 3, 10, 2, 'Initialization, Condition and Update', 6, ARRAY['while-loop'], false, true,
  '[
    {
      "id": "t1",
      "type": "teacher-explanation",
      "content": {
        "title": "The 3 Essentials of a while Loop",
        "content": "1. Initialization: Set loop counter before loop starts.\n2. Condition check: Evaluated before each iteration.\n3. Update: Modify loop variable inside the loop body so condition eventually becomes False!"
      }
    }
  ]'::jsonb
),
(
  'm3-loop-termination', 3, 10, 3, 'Loop Termination', 6, ARRAY['while-loop'], false, true,
  '[
    {
      "id": "t1",
      "type": "teacher-explanation",
      "content": {
        "title": "When Loops Stop",
        "content": "A while loop terminates when its condition becomes False."
      }
    }
  ]'::jsonb
),
(
  'm3-infinite-loops', 3, 10, 4, 'Avoiding Infinite Loops', 5, ARRAY['while-loop'], false, true,
  '[
    {
      "id": "t1",
      "type": "teacher-explanation",
      "content": {
        "title": "Danger of Infinite Loops",
        "content": "If the condition never becomes False (e.g., forgetting `count += 1`), the loop runs forever until program memory or time limits explode."
      }
    }
  ]'::jsonb
),
(
  'm3-while-problems', 3, 10, 5, 'Guided While Problems', 9, ARRAY['while-loop'], false, true,
  '[
    {
      "id": "cp1",
      "type": "code-practice",
      "content": {
        "instruction": "Use a while loop to print numbers 1, 2, 3, 4.",
        "starterCode": "n = 1\nwhile n <= 4:\n    print(n)\n    n += 1",
        "solutionCode": "n = 1\nwhile n <= 4:\n    print(n)\n    n += 1",
        "testCases": [
          { "input": "", "expectedOutput": "1\n2\n3\n4" }
        ]
      }
    }
  ]'::jsonb
),
(
  'm3-sum-digits', 3, 10, 6, 'Sum of Digits', 8, ARRAY['while-loop'], false, true,
  '[
    {
      "id": "t1",
      "type": "teacher-explanation",
      "content": {
        "title": "Digit Processing with % and //",
        "content": "Extract last digit using `num % 10` and remove last digit using `num // 10`.\n\nExample:\nnum = 126\ntotal = 0\nwhile num > 0:\n    total += num % 10\n    num //= 10\nprint(total) # 6 + 2 + 1 = 9"
      }
    }
  ]'::jsonb
),
(
  'm3-while-checkpoint', 3, 10, 7, 'While Loop Checkpoint', 8, ARRAY['while-loop'], false, true,
  '[
    {
      "id": "quiz1",
      "type": "checkpoint-quiz",
      "content": {
        "passingScore": 70,
        "questions": [
          {
            "id": "q1",
            "question": "What happens if a while loop condition is initially False?",
            "options": ["Runs once", "Body never executes", "Infinite loop", "Syntax error"],
            "correctAnswer": 1,
            "explanation": "Condition is checked before entry, so body is skipped."
          }
        ]
      }
    }
  ]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  module_number = EXCLUDED.module_number,
  level_number = EXCLUDED.level_number,
  lesson_order = EXCLUDED.lesson_order,
  title = EXCLUDED.title,
  estimated_minutes = EXCLUDED.estimated_minutes,
  skill_tags = EXCLUDED.skill_tags,
  is_free_preview = EXCLUDED.is_free_preview,
  active = EXCLUDED.active,
  content = EXCLUDED.content;
