-- ==============================================================================
-- ATP REVISION VAULT: AUTO-GENERATED IDENTITY FOR ORDERS.ID
-- ==============================================================================
-- Ensures public.orders.id automatically generates a BIGINT sequence value on insert
-- without requiring the application or Edge Functions to provide an ID manually.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'orders'
      AND column_name = 'id'
      AND is_identity = 'YES'
  ) THEN
    ALTER TABLE public.orders
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;
